{"name": "Something", "status": "broken", "statusDetails": {"message": "support.custom_errors.TokenNotGeneratedError: Failed to retrieve the token. Status code: 403", "trace": "credentials = Credentials(APP_USERNAME='superuser', APP_PASSWORD='password')\n\n    @pytest.fixture(scope=\"session\")\n    def bearer_token(credentials):\n        response = requests.post(f\"{Endpoints.TOKEN_URL}\",\n                                 json={\"username\": credentials.APP_USERNAME, \"password\": credentials.APP_PASSWORD},\n                                 headers={\"Content-Type\": \"application/json\"})\n        if response.status_code == 200:\n            token = response.json().get(\"token\")\n            if token is None:\n                raise NoTokenInResponseError\n            yield token\n        else:\n>           raise TokenNotGeneratedError(response.status_code)\nE           support.custom_errors.TokenNotGeneratedError: Failed to retrieve the token. Status code: 403\n\n../conftest.py:111: TokenNotGeneratedError"}, "description": "new login", "attachments": [{"name": "log", "source": "7f6940e5-1246-4cbe-a1d2-2d35e5f1d91b-attachment.txt", "type": "text/plain"}], "start": 1694464208404, "stop": 1694464208404, "uuid": "278e7e01-3f50-4931-b600-279173fc8cd7", "historyId": "4b73bfba94db569471f0ba5e3cd25709", "testCaseId": "4b73bfba94db569471f0ba5e3cd25709", "fullName": "tests.test_employees#test_get_all_employees", "labels": [{"name": "suite", "value": "Some suite"}, {"name": "owner", "value": "Yura"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "MacBook-Pro-Urij.local"}, {"name": "thread", "value": "1952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_employees"}]}